source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('stuff/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import (welcome_page, LanguageSwitchView, HomePage, LabyrinthListView,
                          LabyrinthDetailView, CategoryListView, TeachTaleDetailView, ParentListView,
                          ParentDetailView, CatalogListView, SearchResult
                          )

urlpatterns = [
    path('', welcome_page, name='welcome'),
    path('lang/', LanguageSwitchView.as_view(), name='lang'),
    path('home/', HomePage.as_view(), name='home'),
    path('labyrinth/', LabyrinthListView.as_view(), name='labyrinth'),
    path('labyrinth/detail/<int:id>/', LabyrinthDetailView.as_view(), name='labyrinth_detail'),
    path('teach_tale/categories/', CategoryListView.as_view(), name='teach_tale_categories'),
    path('teachtale/detail/<int:pk>/', TeachTaleDetailView.as_view(), name='teach_tale_detail'),
    path('parent/', ParentListView.as_view(), name='parent'),
    path('parent/detail/<int:pk>/', ParentDetailView.as_view(), name='parent_detail'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('search/results/', SearchResult.as_view(), name='search'),
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models.signals import post_save
from django.dispatch import receiver


class Author(models.Model):
    name = models.CharField(max_length=25, verbose_name='Автор')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    position = models.CharField(max_length=50, null=True, blank=True, verbose_name='Должность')

    def __str__(self):
        return "{} {}".format(self.name, self.last_name)

    class Meta:
        verbose_name_plural = 'Авторы'


class Labyrinth(MPTTModel):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='labyrinth_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    second_text = models.TextField(max_length=7000, null=True,  verbose_name='Текст')
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    key_to_next_step = models.CharField(max_length=255, blank=True, null=True, 
                                        verbose_name='Ключ к этому шагу лабиринта')

    def get_absolute_url(self):
        return reverse('webapp:labyrinth_detail', kwargs={'id': self.id})

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']

    class Meta:
        verbose_name_plural = 'Лабиринты'


class AnswerToShow(models.Model):
    tale = models.ForeignKey('webapp.Labyrinth', on_delete=models.CASCADE, related_name='answer_variants')
    text = models.TextField(max_length=2000, verbose_name='Текст')
    go_to = models.OneToOneField('webapp.Labyrinth', on_delete=models.CASCADE, related_name='answer_from')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Ответы к сказкам'


class TeachTale(models.Model):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='teach_tale_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    second_text = models.TextField(max_length=7000, null=True, blank=True, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    category = models.ForeignKey('webapp.Category', related_name='teach_tale', blank=True,
                                 null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('webapp:teach_tale_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Обучающие сказки'


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заглавие на русском языке')
    title_kg = models.CharField(max_length=255, null=True, verbose_name='Заглавие на кыргызском языке')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Категория'


class ParentsAdvice(models.Model):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='parent_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    second_text = models.TextField(max_length=7000, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('webapp:parent_detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-id',)
        verbose_name_plural = 'Советы родителям'


class Advice(models.Model):
    parent = models.ForeignKey('webapp.ParentsAdvice', null=True, on_delete=models.SET_NULL,
                               related_name='parent_advice', verbose_name='Советы')
    text = models.CharField(max_length=7000, verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Советы'


@receiver(post_save, sender=Labyrinth)
def create_answer_for_labyrynth_instance(sender, instance, created, **kwargs):

    """ 
    Сигнальная функция для создания ответа к этому шагу лабиринта
    """

    if created:
        if not hasattr(instance, 'parrent'):
            return

        if instance.key_to_next_step:
            answer = AnswerToShow.objects.create(tale=instance.parent, 
                                                 text=instance.key_to_next_step,
                                                 go_to=instance)
        pass
    pass

source/webapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import activate
from django.views.generic import ListView, DetailView
from django import views
from itertools import chain

from webapp.models import Category, Labyrinth, TeachTale, ParentsAdvice


class LanguageSwitchView(views.View):

    def get(self, request, *args, **kwargs):
        lan_code = self.request.GET.get('lang')
        if lan_code in ('ru', 'ky'):
            activate(lan_code)
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('webapp:home')


def welcome_page(request):
    return render(request, 'stories/main.html')


class HomePage(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'stories/index.html'


class TeachTaleDetailView(DetailView):
    model = TeachTale
    context_object_name = 'teach_tale'
    template_name = 'stories/teach_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exclude_id = self.kwargs['pk']
        context['suggestions'] = TeachTale.objects.order_by('-created_at').exclude(id=exclude_id)[:10]
        return context


class LabyrinthListView(ListView):
    model = Labyrinth
    context_object_name = 'labyrinths'
    template_name = 'stories/maze.html'
    paginate_by = 6

    def get_queryset(self):
        return Labyrinth.objects.filter(parent__isnull=True)


class LabyrinthDetailView(views.View):

    def get(self, request, id):
        labyrinth = get_object_or_404(Labyrinth, id=id)
        answers = labyrinth.answer_variants.all()
        return render(request, 'stories/detail.html', context={'labyrinth': labyrinth, 'answers': answers})


class ParentListView(ListView):
    model = ParentsAdvice
    context_object_name = 'parents'
    template_name = 'stories/parent.html'
    paginate_by = 6


class ParentDetailView(DetailView):
    model = ParentsAdvice
    context_object_name = 'parent'
    template_name = 'stories/parent_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exclude_id = self.kwargs['pk']
        context['suggestions'] = ParentsAdvice.objects.order_by('-created_at').exclude(id=exclude_id)[:10]
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'stories/teach_tale.html'
    context_object_name = 'categories'


class CatalogListView(ListView):
    model = Labyrinth
    context_object_name = 'labyrinths'
    template_name = 'stories/catalog.html'
    paginate_by = 6

    def get_queryset(self):
        return Labyrinth.objects.filter(parent__isnull=True)


class SearchResult(views.View):

    def get(self, request):
        search = self.request.GET.get('search_tale')
        modified = search.capitalize()
        if modified == "":
            return render(request, 'stories/search_fail.html')
        teach_tales = TeachTale.objects.filter(Q(title__contains=modified) | Q(author__name__contains=modified))
        parents = ParentsAdvice.objects.filter(Q(title__contains=modified) | Q(author__name__contains=modified))
        labyrinth = Labyrinth.objects.filter(Q(parent__isnull=True), Q(title__contains=modified)
                                             | Q(author__name__contains=modified))
        if teach_tales or parents or labyrinth:
            results = chain(teach_tales, parents, labyrinth)
            data = self.patination(request, val=results)
            return render(request, 'stories/search_success.html', context={'data': data})
        return render(request, 'stories/search_fail.html')

    def patination(self, request, val, *args):
        paginator = Paginator(list(val), 6)
        page = request.GET.get('page', 1)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        return data

source/webapp/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="{% block meta_description %}Smart Jomok{% endblock %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css">

    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7852f64c69.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
    <link rel="icon" href="{% static 'webapp/images/faviconSJ.png' %}">
    <title>{% block title %} Smart jomok {% endblock %}</title>
</head>
<body>
<div class="blur"></div>

<div class="container">

    <header class="header">
        <div class="lang-container">
            <div class="header__lang">
                <a href="{% url 'webapp:lang' %}?lang=ru&next={{ request.build_absolute_uri }}" class="lang__item"
                   id="ru">рус</a>
                <a href="{% url 'webapp:lang' %}?lang=ky&next={{ request.build_absolute_uri }}" class="lang__item"
                   id="kyr">кыр</a>
            </div>
        </div>

        <div class="logo">
            <a href="{% url 'webapp:welcome' %}" class="logo__img">
                <img src="{% static 'webapp/images/logo.png' %}" alt="logo">
            </a>
        </div>

        <nav class="nav" id="sitemaps">
            <div class="nav__menu-toggle" id="mobile-menu">
                <div class="bar bar1"></div>
                <div class="bar bar2"></div>
                <div class="bar bar3"></div>
            </div>
            <ul class="nav__list">
                <li class="nav__item">
                    <img src="../../static/webapp/images/pic-menu1.png" alt="maze">
                    <a href="{% url 'webapp:labyrinth' %}" class="nav__link lang" key="maze">Лабиринт</a>
                </li>
                <li class="nav__item dropdown">
                    <img src="../../static/webapp/images/pic-menu2.png" alt="">
                    <a href="{% url 'webapp:teach_tale_categories' %}" class="nav__link link--submenu lang"
                       key="teaching">
                        Обучающие
                    </a>
                    <ul class="dropdown-menu dropdown-menu__list">
                        {% include 'partial/categories.html' %}
                    </ul>
                </li>
                <li class="nav__item">
                    <img src="../../static/webapp/images/pic-menu3.png" alt="">
                    <a href="{% url 'webapp:parent' %}" class="nav__link lang" key="parents">Родителям</a>
                </li>
            </ul>
        </nav>

        <div class="search">
            <button class="btn show-form">
                <i class="fas fa-search"></i>
            </button>
            <div class="search__popup">
                <form action="{% url 'webapp:search' %}" method="get" class="search__form">
                    <input type="text" name="search_tale" placeholder="Поиск..." value="">
                    <button class=" btn search__btn" type="submit" value="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </header>

    {% block content %}{% endblock %}

    <footer class="footer">
        <div class="footer-wrap">
            <div class="footer__logo">
                <a href="#" class="logo__img">
                    <img src="{% static 'webapp/images/logo.png' %}" alt="logo">
                </a>
            </div>

            <nav class="nav">
                <ul class="nav__list">
                    <li class="nav__item">
                        <a href="{% url 'webapp:labyrinth' %}" class="nav__link  lang" key="maze">Лабиринты</a>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'webapp:teach_tale_categories' %}" class="nav__link lang" key="teaching">
                            Обучающие
                        </a>
                        <ul class="dropdown-menu dropdown-menu__list">
                            {% include 'partial/categories.html' %}
                        </ul>
                    </li>
                    <li class="nav__item">
                        <a href="{% url 'webapp:parent' %}" class="nav__link lang" key="parents">Родителям</a>
                    </li>
                </ul>
            </nav>

            <ul class="social-icon">
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fab fa-vk"></i>
                    </a>
                </li>
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fab fa-facebook-square"></i>
                    </a>
                </li>
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fab fa-twitter"></i>
                    </a>
                </li>
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fab fa-google"></i>
                    </a>
                </li>
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fas fa-at"></i>
                    </a>
                </li>
                <li class="social-icon__item">
                    <a href="#" class="social-icon__link">
                        <i class="fab fa-odnoklassniki special--ok"></i>
                    </a>
                </li>
            </ul>

        </div>
        <div class="copy_right">
            <span>© 2020 / Hackaton / UTL</span>
        </div>
    </footer>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'webapp/js/jquery.breadcrumbs-generator.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="{% static 'webapp/js/translate.js' %}"></script>
<script src="{% static 'webapp/js/index.js' %}"></script>
</body>
</html>