source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('stuff/', admin.site.urls),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import (welcome_page, LanguageSwitchView, HomePage, LabyrinthListView,
                          LabyrinthDetailView, CategoryListView, TeachTaleDetailView, ParentListView,
                          ParentDetailView, CatalogListView, SearchResult
                          )

urlpatterns = [
    path('', welcome_page, name='welcome'),
    path('lang/', LanguageSwitchView.as_view(), name='lang'),
    path('home/', HomePage.as_view(), name='home'),
    path('labyrinth/', LabyrinthListView.as_view(), name='labyrinth'),
    path('labyrinth/detail/<int:id>/', LabyrinthDetailView.as_view(), name='labyrinth_detail'),
    path('teach_tale/categories/', CategoryListView.as_view(), name='teach_tale_categories'),
    path('teachtale/detail/<int:pk>/', TeachTaleDetailView.as_view(), name='teach_tale_detail'),
    path('parent/', ParentListView.as_view(), name='parent'),
    path('parent/detail/<int:pk>/', ParentDetailView.as_view(), name='parent_detail'),
    path('catalog/', CatalogListView.as_view(), name='catalog'),
    path('search/results/', SearchResult.as_view(), name='search'),
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey
from django.db.models.signals import post_save
from django.dispatch import receiver


class Author(models.Model):
    name = models.CharField(max_length=25, verbose_name='Автор')
    last_name = models.CharField(max_length=30, verbose_name='Фамилия')
    position = models.CharField(max_length=50, null=True, blank=True, verbose_name='Должность')

    def __str__(self):
        return "{} {}".format(self.name, self.last_name)

    class Meta:
        verbose_name_plural = 'Авторы'


class Labyrinth(MPTTModel):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='labyrinth_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    second_text = models.TextField(max_length=7000, null=True,  verbose_name='Текст')
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children',
                            on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    key_to_next_step = models.CharField(max_length=255, blank=True, null=True, 
                                        verbose_name='Ключ к этому шагу лабиринта')

    def get_absolute_url(self):
        return reverse('webapp:labyrinth_detail', kwargs={'id': self.id})

    def __str__(self):
        return self.title

    class MPTTMeta:
        order_insertion_by = ['title']

    class Meta:
        verbose_name_plural = 'Лабиринты'


class AnswerToShow(models.Model):
    tale = models.ForeignKey('webapp.Labyrinth', on_delete=models.CASCADE, related_name='answer_variants')
    text = models.TextField(max_length=2000, verbose_name='Текст')
    go_to = models.OneToOneField('webapp.Labyrinth', on_delete=models.CASCADE, related_name='answer_from')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Ответы к сказкам'


class TeachTale(models.Model):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='teach_tale_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    second_text = models.TextField(max_length=7000, null=True, blank=True, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    category = models.ForeignKey('webapp.Category', related_name='teach_tale', blank=True,
                                 null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('webapp:teach_tale_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Обучающие сказки'


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заглавие на русском языке')
    title_kg = models.CharField(max_length=255, null=True, verbose_name='Заглавие на кыргызском языке')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Категория'


class ParentsAdvice(models.Model):
    author = models.ForeignKey('webapp.Author', on_delete=models.CASCADE, null=True, blank=True,
                               related_name='parent_author', verbose_name='Автор сказки')
    title = models.CharField(max_length=255, verbose_name='Заглавие')
    text = models.TextField(max_length=7000, verbose_name='Текст')
    images = models.ImageField(upload_to='uploads', verbose_name='Картинка/Иллюстрация')
    second_text = models.TextField(max_length=7000, verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('webapp:parent_detail', kwargs={'pk': self.id})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('-id',)
        verbose_name_plural = 'Советы родителям'


class Advice(models.Model):
    parent = models.ForeignKey('webapp.ParentsAdvice', null=True, on_delete=models.SET_NULL,
                               related_name='parent_advice', verbose_name='Советы')
    text = models.CharField(max_length=7000, verbose_name='Текст')

    def __str__(self):
        return self.text

    class Meta:
        verbose_name_plural = 'Советы'


@receiver(post_save, sender=Labyrinth)
def create_answer_for_labyrynth_instance(sender, instance, created, **kwargs):

    """ 
    Сигнальная функция для создания ответа к этому шагу лабиринта
    """

    if created:
        if not hasattr(instance, 'parrent'):
            return

        if instance.key_to_next_step:
            answer = AnswerToShow.objects.create(tale=instance.parent, 
                                                 text=instance.key_to_next_step,
                                                 go_to=instance)
        pass
    pass

source/webapp/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import activate
from django.views.generic import ListView, DetailView
from django import views
from itertools import chain

from webapp.models import Category, Labyrinth, TeachTale, ParentsAdvice


class LanguageSwitchView(views.View):

    def get(self, request, *args, **kwargs):
        lan_code = self.request.GET.get('lang')
        if lan_code in ('ru', 'ky'):
            activate(lan_code)
        next = request.GET.get('next')
        if next:
            return redirect(next)
        return redirect('webapp:home')


def welcome_page(request):
    return render(request, 'stories/main.html')


class HomePage(ListView):
    model = Category
    context_object_name = 'categories'
    template_name = 'stories/index.html'


class TeachTaleDetailView(DetailView):
    model = TeachTale
    context_object_name = 'teach_tale'
    template_name = 'stories/teach_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exclude_id = self.kwargs['pk']
        context['suggestions'] = TeachTale.objects.order_by('-created_at').exclude(id=exclude_id)[:10]
        return context


class LabyrinthListView(ListView):
    model = Labyrinth
    context_object_name = 'labyrinths'
    template_name = 'stories/maze.html'
    paginate_by = 6

    def get_queryset(self):
        return Labyrinth.objects.filter(parent__isnull=True)


class LabyrinthDetailView(views.View):

    def get(self, request, id):
        labyrinth = get_object_or_404(Labyrinth, id=id)
        answers = labyrinth.answer_variants.all()
        return render(request, 'stories/detail.html', context={'labyrinth': labyrinth, 'answers': answers})


class ParentListView(ListView):
    model = ParentsAdvice
    context_object_name = 'parents'
    template_name = 'stories/parent.html'
    paginate_by = 6


class ParentDetailView(DetailView):
    model = ParentsAdvice
    context_object_name = 'parent'
    template_name = 'stories/parent_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        exclude_id = self.kwargs['pk']
        context['suggestions'] = ParentsAdvice.objects.order_by('-created_at').exclude(id=exclude_id)[:10]
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'stories/teach_tale.html'
    context_object_name = 'categories'


class CatalogListView(ListView):
    model = Labyrinth
    context_object_name = 'labyrinths'
    template_name = 'stories/catalog.html'
    paginate_by = 6

    def get_queryset(self):
        return Labyrinth.objects.filter(parent__isnull=True)


class SearchResult(views.View):

    def get(self, request):
        search = self.request.GET.get('search_tale')
        modified = search.capitalize()
        if modified == "":
            return render(request, 'stories/search_fail.html')
        teach_tales = TeachTale.objects.filter(Q(title__contains=modified) | Q(author__name__contains=modified))
        parents = ParentsAdvice.objects.filter(Q(title__contains=modified) | Q(author__name__contains=modified))
        labyrinth = Labyrinth.objects.filter(Q(parent__isnull=True), Q(title__contains=modified)
                                             | Q(author__name__contains=modified))
        if teach_tales or parents or labyrinth:
            results = chain(teach_tales, parents, labyrinth)
            data = self.patination(request, val=results)
            return render(request, 'stories/search_success.html', context={'data': data})
        return render(request, 'stories/search_fail.html')

    def patination(self, request, val, *args):
        paginator = Paginator(list(val), 6)
        page = request.GET.get('page', 1)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        return data

source/webapp/templates/stories/catalog.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %} Smart Jomok - All stories {% endblock %}
{% block title %} {% endblock %}
{% block content %}
<div class="breadcrumb catalog--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:home' %}" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item latest lang" key="catalog">
            Каталог сказак
        </li>
    </ol>
</div>

<section class="catalog">
    <div class="card-container card-size">
        {% for labyrinth in labyrinths %}
        <a href="{% url 'webapp:labyrinth_detail' labyrinth.id %}">
            <div class="card-tale">
                <div class="card-tale__photo">
                    <img src="{{ labyrinth.images.url }}" alt="">
                </div>
                <div class="card-tale__info">
                    <h2 class="card-tale__name">{{ labyrinth.title }}</h2>
                    <div class="wrapin">
                        <span class="card-tale__author">
                            {% if labyrinth.author %}{{ labyrinth.author }}{% endif %}
                        </span>
                        <span class="card-tale__category">
                            Лабиринты
                        </span>
                    </div>
                    <p class="card-tale__text">
                        {{ labyrinth.text|truncatewords:20 }}
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
</section>
{% endblock %}

source/webapp/templates/stories/detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}Smart Jomok - Labyrinth {% endblock %}
{% block title %} Smart Jomok | Лабиринт {% endblock %}
{% block content %}
<div class="breadcrumb all--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="index.html" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:labyrinth' %}" class="breadcrumb__link lang" key="maze">Лабиринты</a>
        </li>
        <li class="breadcrumb__item latest dark--clr">
              {{ labyrinth.title }}
                 {% if labyrinth.author %}{{ labyrinth.author }}{% endif %}
        </li>
    </ol>
</div>
<section class="detail">
    <div class="detail-wrapper">
    <h2 class="detail__title">{{ labyrinth.title }}</h2>
        <p class="detail__text">{{ labyrinth.text }}</p>
           <img src="{{ labyrinth.images.url }}" class="detail__image" alt="hedgehog">
        <p class="detail__text">
            {% if labyrinth.second_text %}{{ labyrinth.second_text }}{% endif %}
        </p>
        <div class="btn-block">
            {% if answers %}
                {% for answer in answers %}
                    <a href="{{ answer.go_to.get_absolute_url }}" class="detail__btn">{{ answer.text }}</a>
                {% endfor %}
            {% else %}
                <p class="detail__author">
                    {% if labyrinth.author %}
                        {{ labyrinth.author }}
                    {% endif %}
                </p>
            {% endif %}
        </div>
    </div>

</section>
{% endblock %}

source/webapp/templates/stories/index.html
{% extends 'base.html' %}
{% load  static %}
{% block meta_description %}Smart Jomok - Home page {% endblock %}
{% block content %}
<section class="greeting greeting--mp-full">
    <div class="greeting__left">
        <p class="greeting__title lang" key="greet">Добро пожаловать в</p>
        <h1 class="greeting__title-main">Smart-Jomok!</h1>
        <p class="greeting__info lang" key="info">
            Это сервис для детей и взрослых, который предоставляет возможность
            узнать и понять лучше ребёнка через сказкотерапию.
        </p>
        <a href="{% url 'webapp:catalog' %}" class="greeting__btn lang" key="tale_btn">Перейти к сказкам</a>
    </div>
    <div class="greeting__right">
        <img src="{% static 'webapp/images/main-pic.png' %}" alt="parents">
    </div>
</section>

<section class="category">

    <div class="cards-container">
        <div class="card">
            <a href="{% url 'webapp:labyrinth' %}" class="custom-card">
                <div class="card__photo">
                    <img src="{% static 'webapp/images/labs.png' %}" alt="">
                </div>
                <div class="card__body">
                    <h2 class="card__name lang" key="maze">Лабиринты</h2>
                    <p class="card__description lang" key="text-m">
                        С помощью сказок лабиринтов можно,
                        узнать как мыслит ваш ребенок, для более
                        легкого прохождения имеются варианты.
                    </p>
                </div>
            </a>
        </div>

        <div class="card">
            <a href="{% url 'webapp:teach_tale_categories' %}" class="custom-card">
                <div class="card__photo">
                    <img src="{% static 'webapp/images/book.png' %}" alt="">
                </div>
                <div class="card__body">
                <h2 class="card__name lang" key="teaching">Обучающие</h2>
                <p class="card__description lang" key="text-t">
                    В этой категории собраны сказки по категориям, которые могут обучить
                    Вашего ребенка:
                </p>
                </div>
            </a>
            <ul class="card__list">
                <li class="card__item">
                    <a href="#" class="card__link lang" key="good">
                        Доброте
                    </a>
                </li>
                <li class="card__item">
                    <a href="#" class="card__link lang" key="trying">
                        Старанию
                    </a>
                </li>
                <li class="card__item">
                    <a href="#" class="card__link lang" key="friendship">
                        Дружбе
                    </a>
                </li>
            </ul>
        </div>


        <div class="card">
            <a href="{% url 'webapp:parent' %}" class="custom-card">
                <div class="card__photo">
                    <img src="{% static 'webapp/images/parents.png' %}" alt="">
                </div>
               <div class="card__body">
                   <h2 class="card__name lang" key="parents">Родителям</h2>
                   <p class="card__description lang" key="text-p">
                       Здесь собраны сказки, которые вы можете обсуждать
                       вместе с вашим ребенком. Они побуждают к общению.
                       Вы, как никто другой, можете помочь своему ребенку.
                   </p>
               </div>
            </a>
        </div>
    </div>
</section>
{% endblock %}

source/webapp/templates/stories/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="{% block meta_description %}Smart Jomok{% endblock %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7852f64c69.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'webapp/css/style.css' %}">
    <link rel="icon" href="{% static 'webapp/images/faviconSJ.png' %}">
    <title>{% block title %} Smart jomok {% endblock %}</title>
</head>
<body>
<div class="blur"></div>
<div class="container">
    <header class="header">
        <div class="lang-container">
            <div class="header__lang">
                <a href="{% url 'webapp:lang' %}?lang=ru&next={{ request.build_absolute_uri }}" class="lang__item"
                   id="ru">рус</a>
                <a href="{% url 'webapp:lang' %}?lang=ky&next={{ request.build_absolute_uri }}" class="lang__item"
                   id="kyr">кыр</a>
            </div>
        </div>
        <div class="logo">
            <a href="{% url 'webapp:home' %}" class="logo__img">
                <img src="{% static 'webapp/images/logo.png' %}" alt="logo">
            </a>
        </div>

        <nav class="nav" id="sitemaps">
            <ul class="nav__list">
                <li class="nav__item">
                    <a href="{% url 'webapp:labyrinth' %}" class="nav__link lang" key="maze">Лабиринт</a>
                </li>
                <li class="nav__item dropdown">
                    <a href="{% url 'webapp:teach_tale_categories' %}" class="nav__link link--submenu lang" key="teaching">
                        Обучающие
                    </a>
                    <ul class="dropdown-menu dropdown-menu__list">
                        {% include 'partial/categories.html' %}
                    </ul>
                </li>
                <li class="nav__item">
                    <a href="{% url 'webapp:parent' %}" class="nav__link lang" key="parents">Родителям</a>
                </li>
            </ul>
        </nav>

        <div class="search">
            <button class="btn show-form">
                <i class="fas fa-search"></i>
            </button>
            <div class="search__popup">
                <form action="{% url 'webapp:search' %}" method="get" class="search__form">
                    <input type="text" name="search_tale" placeholder="Поиск..." value="">
                    <button class=" btn search__btn" type="submit" value="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div>
        </div>
    </header>

    <section class="greeting greeting--mp">
        <div class="greeting__left">
            <p class="greeting__title lang" key="greet">Добро пожаловать в</p>
            <h1 class="greeting__title-main">Smart-Jomok!</h1>
            <p class="greeting__info lang" key="info">
                Это сервис для детей и взрослых, который предоставляет возможность
                узнать и понять лучше ребёнка через сказкотерапию.
            </p>
            <a href="{% url 'webapp:home' %}" class="greeting__btn lang" key="tale_btn">Перейти к сказкам</a>
        </div>
        <div class="greeting__right">
            <img src="{% static 'webapp/images/family.png' %}" alt="parents">
        </div>
    </section>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'webapp/js/jquery.breadcrumbs-generator.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"></script>
<script src="{% static 'webapp/js/translate.js' %}"></script>
<script src="{% static 'webapp/js/index.js' %}"></script>
</body>
</html>

source/webapp/templates/stories/maze.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}Smart Jomok - Labyrinth {% endblock %}
{% block title %} {% endblock %}
{% block content %}
<div class="breadcrumb all--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:home' %}" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item latest blue--clr lang" key="maze">
            Лабиринты
        </li>
    </ol>
</div>
<section class="about-maze">
    <h1 class="title lang" key="maze">Лабиринты</h1>
    <div class="about-wrap">
        <p class="text lang" key="text-m">
            С помощью сказок лабиринтов можно, узнать как мыслит ваш ребенок,
            для более легкого прохождения имеются варианты.Lorem ipsum dolor sit amet,
            consectetur adipiscing elit, sed do eiusmod tempor,or sit amet, consectetur adipiscing
        </p>
    </div>
</section>

<section class="maze-tales">
    <div class="card-container card-size">
        {% for labyrinth in labyrinths %}
        <a href="{% url 'webapp:labyrinth_detail' labyrinth.pk %}">
            <div class="card-tale">
                <div class="card-tale__photo">
                    <img src="{{ labyrinth.images.url }}" alt="">
                </div>
                <div class="card-tale__info">
                    <h2 class="card-tale__name">{{ labyrinth.title }}</h2>
                    <div class="wrapin">
                        <span class="card-tale__author">
                            {{ labyrinth.author }}
                        </span>
                    </div>

                    <p class="card-tale__text">
                        {{ labyrinth.text|truncatewords:20 }}
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% if is_paginated %}
    {% include 'partial/pagination.html' %}
    {% endif %}
</section>
{% endblock %}

source/webapp/templates/stories/parent.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}Smart Jomok - Parent Page{% endblock %}
{% block title %} Smart Jomok | Родителям {% endblock %}
{% block content %}
<div class="breadcrumb all--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:home' %}" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item latest blue--clr lang" key="parents">
            Родителям
        </li>
    </ol>
</div>
<section class="about-maze">
    <h1 class="title  lang" key="parents">Родителям</h1>
    <div class="about-wrap">
        <p class="text lang" key="text-p">
            Здесь собраны сказки, которые вы можете обсуждать вместе с вашим ребенком.
            Они побуждают к общению. Вы, как никто другой, можете помочь своему ребенку.
        </p>
    </div>
</section>
<section class="maze-tales card-width">
    <div class="card-container card-size">
        {% for parent in parents %}
        <a href="{% url 'webapp:parent_detail' parent.pk %}">
            <div class="card-tale">
                <div class="card-tale__photo">
                    <img src="{{ parent.images.url }}" alt="">
                </div>
                <div class="card-tale__info">
                    <h2 class="card-tale__name">{{ parent.title }}</h2>
                    <div class="wrapin">
                             <span class="card-tale__author">
                                 {% if parent.author %}{{ parent.author }}{% endif %}
                             </span>
                    </div>
                    <p class="card-tale__text">
                        {{ parent.text }}
                    </p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
    {% if is_paginated %}
    {% include 'partial/pagination.html' %}
    {% endif %}
</section>
{% endblock %}

source/webapp/templates/stories/parent_detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}Smart Jomok - Labyrinth {% endblock %}
{% block title %} Smart Jomok | Родителям {% endblock %}
{% block content %}
<div class="breadcrumb all--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:home' %}" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:teach_tale_categories' %}" class="breadcrumb__link active">Обучающие сказки</a>
        </li>
        <li class="breadcrumb__item latest dark--clr">
            {{ parent.title }}
        </li>
    </ol>
</div>

<section class="detail">
    <div class="detail-wrapper">
        <h2 class="detail__title">{{ parent.title }}</h2>
        <p class="detail__text">{{ parent.text }}</p>

        <img src="{{ parent.images.url }}" class="detail__image" alt="hedgehog">

        <p class="detail__text">
            {{ parent.second_text }}
        </p>
    </div>

    <div class="tales-wrapper">
        <h2 class="main-title">Другие обучающие сказки</h2>
        {% for suggestion in suggestions %}
        <a href="{% url 'webapp:teach_tale_detail' suggestion.pk %}" class="item-link">
            <div class="tale">
                <img class="tale__img" src="{{ suggestion.images.url }}" alt="">
                <div class="tale__description">
                    <h5 class="tale__heading">{{ suggestion.title }}</h5>
                    <p class="tale__text">{{ suggestion.text|truncatewords:10 }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</section>
{% endblock %}

source/webapp/templates/stories/teach_detail.html
{% extends 'base.html' %}
{% load static %}
{% block meta_description %}Smart Jomok - Labyrinth {% endblock %}
{% block title %} Smart Jomok | Обучающие {% endblock %}
{% block content %}
<div class="breadcrumb all--margin">
    <ol class="breadcrumb__list" id="breadcrumbs">
        <li class="breadcrumb__item">
            <a href="index.html" class="breadcrumb__link">
                <i class="fas fa-home"></i>
            </a>
        </li>
        <li class="breadcrumb__item">
            <a href="{% url 'webapp:teach_tale_categories' %}" class="breadcrumb__link active">Обучающие сказки</a>
        </li>
        <li class="breadcrumb__item last-item">
               {{ teach_tale.title }} - {% if teach_tale.author %}{{ teach_tale.author }}{% endif %}
        </li>
    </ol>
</div>

<section class="detail">
    <div class="detail-wrapper">
        <h2 class="detail__title">{{ teach_tale.title }}</h2>
        <p class="detail__text">{{ teach_tale.text }}</p>

        <img src="{{ teach_tale.images.url }}" class="detail__image" alt="hedgehog">

        <p class="detail__text">
            {% if teach_tale.second_text %}{{ teach_tale.second_text }}{% endif %}
        </p>
    </div>
    <div class="tales-wrapper">
        <h2 class="main-title">Другие обучающие сказки</h2>
        {% for suggestion in suggestions %}
        <a href="{% url 'webapp:teach_tale_detail' suggestion.pk %}" class="item-link">
            <div class="tale">
                <img class="tale__img" src="{{ suggestion.images.url }}" alt="">
                <div class="tale__description">
                    <h5 class="tale__heading">{{ suggestion.title }}</h5>
                    <p class="tale__text">{{ suggestion.text|truncatewords:10 }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</section>
{% endblock %}